// Shared brand database for Tourne Mobil competitive intelligence
const brands = [
  {
    name: "Adria Mobil",
    country: "Slovenia",
    founded: 1965,
    hq: "Novo Mesto, Slovenia",
    parent: "Trigano Group",
    website: "adria-mobil.com",
    positioning: "Award-winning Twins. Premium European campervan manufacturer with full ladder from entry-level to off-road AWD.",
    platforms: ["ducato", "crafter", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€55K–€137K",
    priceMin: 55000,
    dealers: "500+",
    dealerCount: 500,
    modelCount: 20,
    models: [
      { name: "Twin 540 SPB", series: "Twin", length: 540, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin 600 SPB", series: "Twin", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin 600 SPB Family", series: "Twin", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin 600 SLB", series: "Twin", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin 640 SLB", series: "Twin", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin 640 SGX", series: "Twin", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin Sports 540 SPB", series: "Twin Sports", length: 540, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Twin Sports 600 SPB", series: "Twin Sports", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Twin Sports 640 SLB", series: "Twin Sports", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Twin Sports 640 SGX", series: "Twin Sports", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Twin Supreme 600 SPB", series: "Twin Supreme", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin Supreme 640 SLB", series: "Twin Supreme", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin Supreme 640 SGX", series: "Twin Supreme", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin Supreme 640 SPB Family", series: "Twin Supreme", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Twin Max 680 SLB", series: "Twin Max", length: 684, seats: 4, berths: 2, chassis: "VW Crafter", poptop: false, fourx4: false },
      { name: "Twin Max 680 SGX", series: "Twin Max", length: 684, seats: 4, berths: 2, chassis: "VW Crafter", poptop: false, fourx4: false },
      { name: "Supertwin 600 SPB", series: "Supertwin 4x4", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Supertwin 600 SPB PopTop", series: "Supertwin 4x4", length: 593, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "Supertwin 700 SGX", series: "Supertwin 4x4", length: 697, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Supertwin 700 SGX PopTop", series: "Supertwin 4x4", length: 697, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
    ]
  },
  {
    name: "Hymer",
    country: "Germany",
    founded: 1957,
    hq: "Bad Waldsee, Germany",
    parent: "Thor Industries (Erwin Hymer Group)",
    website: "hymer.com",
    positioning: "The inventor of the motorhome. Premium German engineering, year-round capability, technological leadership.",
    platforms: ["ducato", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€63K–€120K+",
    priceMin: 63000,
    dealers: "1,200+",
    dealerCount: 1200,
    modelCount: 12,
    models: [
      { name: "Ayers Rock", series: "Campervans Fiat", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Yellowstone 601", series: "Campervans Fiat", length: 601, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Yellowstone 640", series: "Campervans Fiat", length: 640, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Redwood 600", series: "Redwood", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Redwood 601", series: "Redwood", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Grand Canyon S 600", series: "Grand Canyon S", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: true, fourx4: true },
      { name: "Grand Canyon S 700", series: "Grand Canyon S", length: 697, seats: 4, berths: 4, chassis: "Mercedes Sprinter", poptop: true, fourx4: true },
      { name: "Grand Canyon S CrossOver", series: "Grand Canyon S", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "Grand Canyon S Xperience", series: "Grand Canyon S", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Westfalia",
    country: "Germany",
    founded: 1951,
    hq: "Rheda-Wiedenbrück, Germany",
    parent: "Rapido Group",
    website: "westfalia-mobil.com",
    positioning: "The historic designer of top-of-the-range camper vans. Heritage + premium since 1951.",
    platforms: ["ducato", "sprinter", "crafter", "transit"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€70K–€135K",
    priceMin: 70000,
    dealers: "100+",
    dealerCount: 100,
    modelCount: 9,
    models: [
      { name: "Columbus 540D", series: "Columbus", length: 540, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Columbus 600D", series: "Columbus", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Columbus 600E", series: "Columbus", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Columbus 640E", series: "Columbus", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "James Cook 600D", series: "James Cook", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: true },
      { name: "James Cook 600E", series: "James Cook", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: true },
      { name: "Sven Hedin", series: "Sven Hedin", length: 599, seats: 4, berths: 2, chassis: "MAN TGE", poptop: true, fourx4: true },
      { name: "Kipling", series: "Kipling", length: 545, seats: 4, berths: 4, chassis: "Ford Transit Custom", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Knaus",
    country: "Germany",
    founded: 1960,
    hq: "Jandelsbrunn, Germany",
    parent: "Knaus Tabbert AG",
    website: "knaus.com",
    positioning: "Freedom that inspires. Premium quality made in Germany, tradition and innovation.",
    platforms: ["ducato", "crafter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€65K–€90K+",
    priceMin: 65000,
    dealers: "350+",
    dealerCount: 350,
    modelCount: 10,
    models: [
      { name: "Boxlife 540 MQ", series: "Boxlife", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Boxlife 600 MQ", series: "Boxlife", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Boxlife 600 DQ", series: "Boxlife", length: 599, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Boxlife 600 ME", series: "Boxlife", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Boxlife 630 ME", series: "Boxlife", length: 630, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Boxlife Pro 540 Road", series: "Boxlife Pro", length: 541, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Boxlife Pro 600 Street", series: "Boxlife Pro", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Boxlife Pro 600 Street XL", series: "Boxlife Pro", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Boxdrive 600 XL", series: "Boxdrive", length: 598, seats: 4, berths: 4, chassis: "MAN TGE", poptop: false, fourx4: true },
      { name: "Boxdrive 680 ME", series: "Boxdrive", length: 684, seats: 4, berths: 2, chassis: "MAN TGE", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Malibu",
    country: "Germany",
    founded: 1980,
    hq: "Aulendorf, Germany",
    parent: "Carthago Group",
    website: "malibu-carthago.com",
    positioning: "The number-one premium camper van. Innovative extra benefits and first-class equipment.",
    platforms: ["ducato", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€52K–€100K+",
    priceMin: 52000,
    dealers: "250+",
    dealerCount: 250,
    modelCount: 10,
    models: [
      { name: "Compact 540 DB", series: "Van Compact", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Compact 600 LE", series: "Van Compact", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Comfort 600 DB", series: "Van Comfort", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Comfort 640 LE", series: "Van Comfort", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Diversity 600 DB K", series: "Van Diversity", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Diversity 640 LE K", series: "Van Diversity", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "First Class 640 LE RB", series: "First Class", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Relax 640 LE R", series: "Relax", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Genius 641 LE", series: "Genius", length: 641, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
      { name: "Genius Performance 4x4", series: "Genius", length: 641, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
    ]
  },
  {
    name: "CROSSCAMP",
    country: "Germany",
    founded: 2019,
    hq: "Isny im Allgäu, Germany",
    parent: "Erwin Hymer Group / Dethleffs",
    website: "crosscamp.com",
    positioning: "Urban Outdoors. Intersection of city life and outdoor adventure for younger buyers.",
    platforms: ["ducato", "peugeot", "opel"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€44K–€62K",
    priceMin: 44000,
    dealers: "350+",
    dealerCount: 350,
    modelCount: 7,
    models: [
      { name: "EXPLR (Opel Zafira)", series: "Urban Camper", length: 495, seats: 7, berths: 4, chassis: "Opel Zafira Life", poptop: true, fourx4: false },
      { name: "EXPLR (Peugeot)", series: "Urban Camper", length: 495, seats: 7, berths: 4, chassis: "Peugeot Traveller", poptop: true, fourx4: false },
      { name: "ADVTR 5.41", series: "Camper Van", length: 541, seats: 4, berths: 2, chassis: "Opel Movano / Fiat Ducato / Peugeot Boxer", poptop: true, fourx4: false },
      { name: "ADVTR 6.0 DF", series: "Camper Van", length: 600, seats: 4, berths: 4, chassis: "Opel Movano / Fiat Ducato / Peugeot Boxer", poptop: true, fourx4: false },
      { name: "ADVTR 6.4 EF", series: "Camper Van", length: 636, seats: 4, berths: 4, chassis: "Opel Movano / Fiat Ducato / Peugeot Boxer", poptop: true, fourx4: false },
      { name: "EXPDN 7.0 E", series: "Low-Profile", length: 699, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
      { name: "EXPDN 7.4 E", series: "Low-Profile", length: 740, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Dethleffs",
    country: "Germany",
    founded: 1931,
    hq: "Isny im Allgäu, Germany",
    parent: "Erwin Hymer Group / Thor Industries",
    website: "dethleffs.com",
    positioning: "Your caravanning partner. Inventor of the German caravan. Experience freedom, flexibility and comfort.",
    platforms: ["ducato", "peugeot", "transit", "crafter"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€77K",
    priceMin: 55000,
    dealers: "650+",
    dealerCount: 650,
    modelCount: 14,
    models: [
      { name: "Globetrail 540 DR", series: "Classic/Advantage", length: 540, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 600 DK", series: "Classic/Advantage", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 600 DS", series: "Classic/Advantage", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 600 DR", series: "Classic/Advantage", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 600 ER", series: "Classic/Advantage", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 590 C", series: "Classic", length: 590, seats: 4, berths: 2, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "Globetrail 640 EK", series: "Classic/Advantage", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 640 ER", series: "Classic/Advantage", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 640 ES", series: "Classic/Advantage", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail 640 HR", series: "Classic/Advantage", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail Active 600 KS", series: "Active", length: 599, seats: 4, berths: 6, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail Active 640 ES", series: "Active", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato / Citroën Jumper", poptop: true, fourx4: false },
      { name: "Globetrail Performance 600 DR", series: "Performance", length: 599, seats: 4, berths: 3, chassis: "VW Crafter", poptop: true, fourx4: false },
      { name: "Globetrail 75k Iconic 640 HR", series: "Iconic Edition", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Bravia Mobil",
    country: "Slovenia",
    founded: 2005,
    hq: "Straža / Novo Mesto, Slovenia",
    parent: "Independent (family-owned)",
    website: "bravia-mobil.com",
    positioning: "Life is a journey. Enjoy the ride. Premium panel-van campervans with in-house solid wood furniture.",
    platforms: ["peugeot", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€75K–€90K+",
    priceMin: 75000,
    dealers: "30+",
    dealerCount: 30,
    modelCount: 8,
    models: [
      { name: "Swan 495", series: "Swan", length: 496, seats: 7, berths: 4, chassis: "Peugeot Traveller", poptop: true, fourx4: false },
      { name: "Swan 599", series: "Swan", length: 600, seats: 4, berths: 3, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Swan 599 Narvik", series: "Swan", length: 600, seats: 4, berths: 3, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Swan 599 Pop-Up", series: "Swan", length: 600, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: true, fourx4: false },
      { name: "Swan 636", series: "Swan", length: 636, seats: 4, berths: 3, chassis: "Peugeot Boxer", poptop: true, fourx4: false },
      { name: "Swan 680", series: "Swan", length: 684, seats: 4, berths: 3, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Swan 699", series: "Swan", length: 699, seats: 4, berths: 4, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Mega Mobil",
    country: "Slovenia",
    founded: 2014,
    hq: "Slovenska Bistrica, Slovenia",
    parent: "MegaTektil d.o.o. (family-owned)",
    website: "megamobil.si",
    positioning: "Premium, handcrafted, individually configurable campervans. Patented comfort bathroom. 4-season builds.",
    platforms: ["ducato", "peugeot", "opel", "crafter", "sprinter"],
    has4x4: true,
    hasPoptop: false,
    priceRange: "€88K–€142K",
    priceMin: 88000,
    dealers: "20+",
    dealerCount: 20,
    modelCount: 15,
    models: [
      { name: "Classic 600", series: "Classic", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato / Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Classic 600 Hubbett", series: "Classic", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Classic 600 MAX Hubbett", series: "Classic", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Classic 600 Twin", series: "Classic", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Classic 600 Lounge", series: "Classic", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Classic 600 S Lounge", series: "Classic", length: 600, seats: 4, berths: 3, chassis: "MAN TGE / VW Crafter 4x4", poptop: false, fourx4: true },
      { name: "Lounge 540", series: "Lounge", length: 541, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Lounge 600", series: "Lounge", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato / MAN TGE", poptop: false, fourx4: false },
      { name: "Lounge 640", series: "Lounge", length: 636, seats: 4, berths: 3, chassis: "Peugeot Boxer L4H3", poptop: false, fourx4: false },
      { name: "Lounge 680 S", series: "Lounge", length: 684, seats: 4, berths: 3, chassis: "MAN TGE 4x4", poptop: false, fourx4: true },
      { name: "Re-Aktiv 680 S", series: "Re-Aktiv", length: 684, seats: 4, berths: 3, chassis: "MAN TGE / VW Crafter 4x4", poptop: false, fourx4: true },
      { name: "Re-Aktiv 680 S H4", series: "Re-Aktiv", length: 684, seats: 4, berths: 4, chassis: "MAN TGE / VW Crafter 4x4", poptop: false, fourx4: true },
      { name: "Re-Aktiv 700 MAX", series: "Re-Aktiv", length: 697, seats: 4, berths: 4, chassis: "MAN TGE / Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Revolution 640", series: "Revolution", length: 636, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Sport 640 Hubbett", series: "Sport", length: 636, seats: 4, berths: 3, chassis: "Peugeot Boxer / Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Tourne Mobil",
    country: "Slovenia",
    founded: 2020,
    hq: "Pivka, Slovenia",
    parent: "Independent",
    website: "tourne-mobil.com",
    positioning: "An exciting, intelligent, custom-fitted campervan that changes the way we think about mobility.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "N/A",
    priceMin: 0,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 4,
    highlight: true,
    models: [
      { name: "Select 6.0", series: "Select", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Select 6.4", series: "Select", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Cruise 6.0", series: "Cruise", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Cruise 6.4", series: "Cruise", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Dreamer",
    country: "France",
    founded: 2006,
    hq: "Mayenne, France",
    parent: "Rapido Group",
    website: "dreamer-van.com",
    positioning: "Another idea of freedom. Compact, modern, adventure-ready campervans with Rapido Group heritage.",
    platforms: ["ducato", "peugeot", "transit"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€82K",
    priceMin: 55000,
    dealers: "30+",
    dealerCount: 30,
    modelCount: 16,
    models: [
      { name: "D43 Fun", series: "Fun", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D43 UP Fun", series: "Fun", length: 541, seats: 4, berths: 4, chassis: "Fiat Ducato / Peugeot Boxer", poptop: true, fourx4: false },
      { name: "D55 Fun", series: "Fun", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D68 Fun", series: "Fun", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Camper Sport Fun", series: "Fun", length: 640, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D43 Select", series: "Select", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D43 UP Select", series: "Select", length: 541, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: true, fourx4: false },
      { name: "D55 Select", series: "Select", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D62 Select", series: "Select", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "D68 UP Select", series: "Select", length: 636, seats: 4, berths: 4, chassis: "Peugeot Boxer", poptop: true, fourx4: false },
      { name: "Family Van Select", series: "Select", length: 599, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Camper Van XL Select", series: "Select", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Cap Land Select", series: "Select", length: 545, seats: 4, berths: 4, chassis: "Ford Transit Custom", poptop: false, fourx4: false },
      { name: "City Camp Select", series: "Select", length: 540, seats: 6, berths: 2, chassis: "Ford Transit Custom", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Randger",
    country: "France",
    founded: 2017,
    hq: "Brantôme, Dordogne, France",
    parent: "Trigano Group",
    website: "randger.com",
    positioning: "French designer of converted vans for adventurers. Young, disruptive brand.",
    platforms: ["ducato", "transit"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€63K–€76K",
    priceMin: 63000,
    dealers: "50+",
    dealerCount: 50,
    modelCount: 9,
    models: [
      { name: "R530", series: "R-Series", length: 534, seats: 4, berths: 3, chassis: "Ford Transit Custom", poptop: true, fourx4: false },
      { name: "R540", series: "R-Series", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "R550", series: "R-Series", length: 548, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "R555", series: "R-Series", length: 599, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "R560 4x4", series: "R-Series", length: 598, seats: 4, berths: 2, chassis: "Ford Transit AWD", poptop: false, fourx4: true },
      { name: "R600", series: "R-Series", length: 599, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "R602", series: "R-Series", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "R640", series: "R-Series", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "N616", series: "Special", length: 515, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "La Strada",
    country: "Germany",
    founded: 1986,
    hq: "Echzell, Hesse, Germany",
    parent: "Independent (~50 employees, ~300 units/year)",
    website: "lastrada-mobile.de",
    positioning: "Your German manufacturer of premium motorhomes. Premium compact motorhome manufactory since 1986. Handbuilt, boutique scale.",
    platforms: ["ducato", "sprinter"],
    has4x4: true,
    hasPoptop: false,
    priceRange: "€76K–€161K",
    priceMin: 76000,
    dealers: "30+",
    dealerCount: 30,
    modelCount: 13,
    models: [
      { name: "Avanti L", series: "Avanti", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti XL", series: "Avanti", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti E", series: "Avanti", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti C", series: "Avanti", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti F", series: "Avanti", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti H", series: "Avanti", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti H Plus", series: "Avanti", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti EB", series: "Avanti", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Avanti EBF", series: "Avanti", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Regent E", series: "Regent", length: 599, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
      { name: "Regent S", series: "Regent", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Regent EB", series: "Regent", length: 697, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
      { name: "Nova M", series: "Nova", length: 646, seats: 4, berths: 3, chassis: "Mercedes Sprinter AWD (GRP monocoque)", poptop: false, fourx4: true },
      { name: "Nova EB", series: "Nova", length: 699, seats: 4, berths: 2, chassis: "Mercedes Sprinter (GRP monocoque)", poptop: false, fourx4: false },
    ]
  },
  {
    name: "North Cape",
    country: "Spain",
    founded: 2022,
    hq: "Gijón, Asturias, Spain",
    parent: "Independent (startup)",
    website: "northcape4x4.com",
    positioning: "The adventure is now. Premium Made-in-Spain 4x4 campervans. Design, exclusivity, and uncompromising off-road capability.",
    platforms: ["crafter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€130K–€135K",
    priceMin: 130000,
    dealers: "10+",
    dealerCount: 10,
    modelCount: 4,
    models: [
      { name: "Adventure 6XT", series: "Adventure", length: 599, seats: 4, berths: 2, chassis: "MAN TGE 4x4", poptop: false, fourx4: true },
      { name: "Adventure 6XH", series: "Adventure", length: 599, seats: 4, berths: 2, chassis: "MAN TGE 4x4", poptop: false, fourx4: true },
      { name: "Adventure 6XHT", series: "Adventure", length: 599, seats: 4, berths: 2, chassis: "MAN TGE 4x4", poptop: false, fourx4: true },
      { name: "Adventure 6XR", series: "Adventure", length: 599, seats: 4, berths: 4, chassis: "MAN TGE 4x4", poptop: true, fourx4: true },
    ]
  },
  {
    name: "Globe Traveller",
    country: "Poland",
    founded: 2009,
    hq: "Kraków, Poland",
    parent: "Zasada Group (Elcamp)",
    website: "globe-traveller.eu",
    positioning: "Premium, fully winterised campervans. Innovation, quality and customer satisfaction. Founded by Poland's most decorated rally driver.",
    platforms: ["ducato", "peugeot", "crafter"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€91K–€135K",
    priceMin: 91000,
    dealers: "10+",
    dealerCount: 10,
    modelCount: 14,
    models: [
      { name: "Falcon 2XS", series: "Falcon", length: 599, seats: 2, berths: 2, chassis: "VW Crafter L3H2", poptop: false, fourx4: false },
      { name: "Falcon 2Z", series: "Falcon", length: 684, seats: 2, berths: 2, chassis: "VW Crafter L4H3", poptop: false, fourx4: false },
      { name: "Voyager XS", series: "Voyager", length: 599, seats: 4, berths: 4, chassis: "Fiat Ducato / Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Voyager Z", series: "Voyager", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato / Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Voyager X", series: "Voyager", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato / Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Pathfinder XS", series: "Pathfinder", length: 599, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Pathfinder Z", series: "Pathfinder", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Pathfinder Z Bike", series: "Pathfinder", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Pathfinder X", series: "Pathfinder", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Explorer XS", series: "Explorer", length: 599, seats: 2, berths: 2, chassis: "Fiat Ducato / Peugeot Boxer", poptop: false, fourx4: false },
      { name: "Explorer Z", series: "Explorer", length: 636, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Explorer Z EVO", series: "Explorer", length: 636, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Explorer Z Bike", series: "Explorer", length: 636, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Explorer X", series: "Explorer", length: 636, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Adventure Van Conversions",
    country: "Poland",
    founded: 2016,
    hq: "Królowa Polska, Poland",
    parent: "Independent",
    website: "adventurevanconversions.com",
    positioning: "Explore the world without compromises. All models feature pop-top + 4x4. In harmony with nature.",
    platforms: ["sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€90K+",
    priceMin: 90000,
    dealers: "N/A",
    dealerCount: 0,
    modelCount: 3,
    models: [
      { name: "GT Rebel", series: "GT", length: 593, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "Summit XL", series: "Summit", length: 697, seats: 5, berths: 5, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "Chogori", series: "Chogori", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
    ]
  },
  {
    name: "Pössl",
    country: "Germany",
    founded: 1989,
    hq: "Ainring, Upper Bavaria, Germany",
    parent: "Glück Group (~17,000 vehicles/year group-wide)",
    website: "poessl-mobile.de",
    positioning: "The Original. Inventor of the modern panel-van camper (1989). Affordable, practical, German quality. European market leader in camper van segment.",
    platforms: ["ducato", "peugeot", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€49K–€100K+",
    priceMin: 49000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 30,
    models: [
      { name: "Roadcamp R", series: "D-Line", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "2Win", series: "D-Line", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "2Win R", series: "D-Line", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "2Win S", series: "D-Line", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadstar 600 L", series: "D-Line", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadcruiser", series: "D-Line", length: 635, seats: 4, berths: 3, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadcruiser XL", series: "D-Line", length: 640, seats: 4, berths: 4, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadcruiser Revolution", series: "D-Line", length: 635, seats: 4, berths: 3, chassis: "Fiat Ducato H3 / Citroën Jumper H3", poptop: false, fourx4: false },
      { name: "Trenta 600", series: "Trenta", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Trenta 640", series: "Trenta", length: 635, seats: 4, berths: 3, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Concorde Compact", series: "H-Line", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato H2", poptop: false, fourx4: false },
      { name: "2Win Vario", series: "H-Line", length: 599, seats: 4, berths: 2, chassis: "Fiat Ducato H2", poptop: false, fourx4: false },
      { name: "Vario 545", series: "H-Line", length: 545, seats: 4, berths: 2, chassis: "Fiat Ducato H2", poptop: false, fourx4: false },
      { name: "Summit 600", series: "Summit", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit 600 L", series: "Summit", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit 640", series: "Summit", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit Shine 600", series: "Summit", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit Prime 600", series: "Summit", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Roadstar X", series: "X-Line", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Roadstar XT", series: "X-Line", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Campster", series: "Vanline", length: 495, seats: 5, berths: 4, chassis: "Citroën Spacetourer / Peugeot Traveller", poptop: true, fourx4: false },
      { name: "Vanster", series: "Vanline", length: 495, seats: 8, berths: 4, chassis: "Citroën Spacetourer / Peugeot Traveller", poptop: true, fourx4: false },
      { name: "E-Vanster", series: "Vanline", length: 495, seats: 5, berths: 2, chassis: "Citroën SpaceTourer Electric", poptop: true, fourx4: false },
      { name: "Vanstar", series: "Vanline", length: 514, seats: 5, berths: 4, chassis: "Mercedes Vito Tourer", poptop: true, fourx4: false },
      { name: "Campstar", series: "Vanline", length: 514, seats: 5, berths: 4, chassis: "Mercedes V-Class", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Bavaria",
    country: "Germany",
    founded: 2010,
    hq: "Germany",
    parent: "Independent",
    website: "bavaria-camp.de",
    positioning: "Great variety, modern design, superior quality. Compact campervans with thoughtful layouts.",
    platforms: ["ducato"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€67K–€70K",
    priceMin: 67000,
    dealers: "N/A",
    dealerCount: 0,
    modelCount: 5,
    models: [
      { name: "K600S Bavaria", series: "K-Series", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: true },
      { name: "K600G Nomad", series: "K-Series", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: true },
      { name: "K600J", series: "K-Series", length: 600, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "K630J", series: "K-Series", length: 630, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Womondo",
    country: "Slovenia",
    founded: 2024,
    hq: "Slovenia",
    parent: "Robeta",
    website: "womondo-by-robeta.com",
    positioning: "New entrant in the Slovenian campervan market. By Robeta.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "N/A",
    priceMin: 0,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 2,
    models: []
  },
  // ══════════ ADDITIONAL BRANDS FROM WAGONCAT ══════════
  {
    name: "Robeta",
    country: "Slovenia",
    founded: 2011,
    hq: "Slovenia",
    parent: "Independent",
    website: "robetamobil.com",
    positioning: "Top 3 manufacturers in Europe in the highest quality class of vans.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "N/A",
    priceMin: 0,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 6,
    models: [
      { name: "New Adonis", series: "Robeta", length: 593, seats: 4, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
      { name: "Apollo", series: "Robeta", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Kronos", series: "Robeta", length: 600, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Helios", series: "Robeta", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Dionysus", series: "Robeta", length: 541, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Ares", series: "Robeta", length: 541, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Sunlight",
    country: "Germany",
    founded: 2001,
    hq: "Leutkirch, Germany",
    parent: "Erwin Hymer Group / Thor Industries",
    website: "sunlight.de",
    positioning: "Affordable entry into campervan life. CLIFF series for adventure seekers.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€50K–€70K",
    priceMin: 50000,
    dealers: "300+",
    dealerCount: 300,
    modelCount: 8,
    models: [
      { name: "CLIFF X 640", series: "CLIFF X", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CLIFF X 600", series: "CLIFF X", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CLIFF 640 RT Adventure", series: "CLIFF RT", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CLIFF 600 RT Adventure", series: "CLIFF RT", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CLIFF 540 RT Adventure", series: "CLIFF RT", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CLIFF 601 Adventure", series: "CLIFF", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "CLIFF 600 Adventure", series: "CLIFF", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "CLIFF 540 Adventure", series: "CLIFF", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Weinsberg",
    country: "Germany",
    founded: 1969,
    hq: "Germany",
    parent: "Knaus Tabbert AG",
    website: "weinsberg.com",
    positioning: "CaraBus and CaraTour series. Value-oriented campervans from Germany's largest RV group.",
    platforms: ["ducato", "transit"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€50K–€70K",
    priceMin: 50000,
    dealers: "300+",
    dealerCount: 300,
    modelCount: 20,
    models: [
      { name: "X-PEDITION 600 MQ", series: "X-PEDITION", length: 630, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "CaraTour 630 ME", series: "CaraTour", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraTour 600 MQ", series: "CaraTour", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraTour 600 DQ", series: "CaraTour", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "CaraTour 540 MQ", series: "CaraTour", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraTour Ford 600 MQ", series: "CaraTour Ford", length: 598, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "CaraTour Ford 550 MQ", series: "CaraTour Ford", length: 553, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "CaraBus 630 ME", series: "CaraBus", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraBus 600 MQ", series: "CaraBus", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraBus 600 DQ", series: "CaraBus", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "CaraBus 540 MQ", series: "CaraBus", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CaraBus Ford 600 MQ", series: "CaraBus Ford", length: 599, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "CaraLife", series: "CaraLife", length: 636, seats: 3, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Van Tourer",
    country: "Germany",
    founded: 2015,
    hq: "Germany",
    parent: "EuroCaravaning",
    website: "vantourer.de",
    positioning: "City-suitable panel vans and compact camping vans. Compact dimensions, modern design.",
    platforms: ["ducato", "transit", "crafter", "sprinter"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€80K",
    priceMin: 55000,
    dealers: "50+",
    dealerCount: 50,
    modelCount: 4,
    models: [
      { name: "630 L", series: "Van Tourer", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "600 L", series: "Van Tourer", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "600 D", series: "Van Tourer", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "540 D", series: "Van Tourer", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Karmann Mobil",
    country: "Germany",
    founded: 1977,
    hq: "Sprendlingen, Germany",
    parent: "Independent",
    website: "karmann-mobil.de",
    positioning: "Dexter and Davis series. Premium German campervans with 4x4 options.",
    platforms: ["ducato", "sprinter"],
    has4x4: true,
    hasPoptop: false,
    priceRange: "€60K–€100K+",
    priceMin: 60000,
    dealers: "30+",
    dealerCount: 30,
    modelCount: 16,
    models: [
      { name: "Dexter 570", series: "Dexter", length: 598, seats: 4, berths: 3, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Dexter 560", series: "Dexter", length: 598, seats: 4, berths: 3, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "Dexter 625", series: "Dexter", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Dexter 600", series: "Dexter", length: 600, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Dexter 580", series: "Dexter", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Dexter 550", series: "Dexter", length: 548, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Davis 630 Lifestyle", series: "Davis", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Davis 600 Lifestyle", series: "Davis", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Davis 591 Lifestyle", series: "Davis", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Davis 540 Lifestyle", series: "Davis", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Carado",
    country: "Germany",
    founded: 2005,
    hq: "Leutkirch im Allgäu, Germany",
    parent: "Erwin Hymer Group / Thor Industries",
    website: "carado.com",
    positioning: "Smart and affordable campervans. CV PRO series with pop-top options.",
    platforms: ["ducato", "transit"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€50K–€70K",
    priceMin: 50000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 5,
    models: [
      { name: "CV640 PRO", series: "CV PRO", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CV601 PRO", series: "CV PRO", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CV600 PRO", series: "CV PRO", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CV540 PRO", series: "CV PRO", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "CV590", series: "CV", length: 598, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: true },
    ]
  },
  {
    name: "Hobby",
    country: "Germany",
    founded: 1967,
    hq: "Fockbek, Germany",
    parent: "Hobby-Wohnwagenwerk",
    website: "hobby-caravan.de",
    positioning: "Entry-level to premium camper vans. ONTOUR, PRESTIGE and Maxia series.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€55K–€80K",
    priceMin: 55000,
    dealers: "400+",
    dealerCount: 400,
    modelCount: 8,
    models: [
      { name: "PRESTIGE VAN 640 ET", series: "Prestige", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "ONTOUR VAN 640 ET", series: "OnTour", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "ONTOUR VAN 600 FT", series: "OnTour", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Maxia Van 680 ET", series: "Maxia", length: 684, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Maxia Van 680 DT", series: "Maxia", length: 684, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Roller Team",
    country: "Italy",
    founded: 2001,
    hq: "San Gimignano, Italy",
    parent: "Trigano Group",
    website: "rollerteam.it",
    positioning: "Livingstone series. Italian-built campervans across three trim levels.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€50K–€70K",
    priceMin: 50000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 17,
    models: [
      { name: "Livingstone Sport DUO XL", series: "Sport", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Livingstone Sport 6", series: "Sport", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Livingstone Sport 5", series: "Sport", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Livingstone Advance DUO XL", series: "Advance", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Livingstone Advance 5", series: "Advance", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Livingstone K2", series: "Livingstone", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Livingstone 6", series: "Livingstone", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Livingstone DUO", series: "Livingstone", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Laika",
    country: "Italy",
    founded: 1964,
    hq: "San Casciano, Italy",
    parent: "Erwin Hymer Group / Thor Industries",
    website: "laika.it",
    positioning: "Italian craftsmanship combining aesthetics and technology. Ecovip flagship series.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€70K–€90K",
    priceMin: 70000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 3,
    models: [
      { name: "Ecovip 645", series: "Ecovip", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Ecovip 600", series: "Ecovip", length: 600, seats: 2, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Ecovip 540", series: "Ecovip", length: 541, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Swift",
    country: "UK",
    founded: 1964,
    hq: "Cottingham, UK",
    parent: "Swift Group",
    website: "swiftgroup.co.uk",
    positioning: "British-built campervans. Carrera and Trekker series with Ford Transit base and 4x4.",
    platforms: ["transit"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "£60K–£85K",
    priceMin: 60000,
    dealers: "100+",
    dealerCount: 100,
    modelCount: 7,
    models: [
      { name: "Carrera 194", series: "Carrera", length: 636, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: true },
      { name: "Carrera 184", series: "Carrera", length: 636, seats: 4, berths: 4, chassis: "Ford Transit", poptop: false, fourx4: true },
      { name: "Carrera 144", series: "Carrera", length: 600, seats: 4, berths: 3, chassis: "Ford Transit", poptop: false, fourx4: true },
      { name: "Carrera 132", series: "Carrera", length: 636, seats: 2, berths: 2, chassis: "Ford Transit", poptop: false, fourx4: true },
      { name: "Carrera 122", series: "Carrera", length: 600, seats: 2, berths: 2, chassis: "Ford Transit", poptop: false, fourx4: true },
      { name: "Trekker X", series: "Trekker", length: 598, seats: 4, berths: 4, chassis: "Ford Transit", poptop: true, fourx4: true },
      { name: "Trekker", series: "Trekker", length: 553, seats: 4, berths: 4, chassis: "Ford Transit", poptop: true, fourx4: true },
    ]
  },
  {
    name: "Pilote",
    country: "France",
    founded: 1962,
    hq: "La Limouzinière, France",
    parent: "Pilote Group",
    website: "pilote-motorhome.uk",
    positioning: "Innovation and experience, industrial processes and artisanal methods combined.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€80K",
    priceMin: 55000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 8,
    models: [
      { name: "V630M", series: "V-Series", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V600G", series: "V-Series", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "V600S", series: "V-Series", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "V600J", series: "V-Series", length: 600, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V540G", series: "V-Series", length: 541, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Globecar",
    country: "Germany",
    founded: 2005,
    hq: "Germany",
    parent: "Pössl / Glück Group",
    website: "globecar.co.uk",
    positioning: "Truly multi-functional. Redefines the motorhome class on a panel van conversion.",
    platforms: ["ducato", "peugeot"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€50K–€70K",
    priceMin: 50000,
    dealers: "100+",
    dealerCount: 100,
    modelCount: 10,
    models: [
      { name: "Campscout Elegance", series: "Campscout", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadscout Elegance", series: "Roadscout", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Roadscout R Elegance", series: "Roadscout", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato / Citroën Jumper", poptop: false, fourx4: false },
      { name: "Summit Prime 640", series: "Summit", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit Prime 600", series: "Summit", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit Shine 640", series: "Summit", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Summit Shine 600", series: "Summit", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Forster",
    country: "Germany",
    founded: 2012,
    hq: "Sprendlingen, Germany",
    parent: "Independent",
    website: "forster-reisemobile.de",
    positioning: "Livin' up series. German-built campervans from compact to family layouts.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€50K–€65K",
    priceMin: 50000,
    dealers: "50+",
    dealerCount: 50,
    modelCount: 6,
    models: [
      { name: "FV 636 EBL", series: "Livin' up", length: 636, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "FV 599 VBL", series: "Livin' up", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "FV 599 HBL", series: "Livin' up", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "FV 599 EBL", series: "Livin' up", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "FV 541 HBL", series: "Livin' up", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "FV 541 Youngster Sunny", series: "Youngster", length: 541, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Clever Vans",
    country: "Germany",
    founded: 2008,
    hq: "Gräfelfing, Germany",
    parent: "Independent",
    website: "clever-mobile.de",
    positioning: "Robust and well thought-out design. Practical campervans with competitive pricing.",
    platforms: ["ducato"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€45K–€65K",
    priceMin: 45000,
    dealers: "30+",
    dealerCount: 30,
    modelCount: 9,
    models: [
      { name: "Celebration 600", series: "Celebration", length: 600, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: true },
      { name: "Drive 600", series: "Drive", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Drive 540", series: "Drive", length: 541, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Runner 636", series: "Runner", length: 636, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Vario Kids 600", series: "Vario", length: 600, seats: 5, berths: 7, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Spirit 600", series: "Spirit", length: 600, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Tour 540", series: "Tour", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Challenger",
    country: "France",
    founded: 1985,
    hq: "Tournon-sur-Rhône, France",
    parent: "Trigano Group",
    website: "challenger-motorhomes.com",
    positioning: "A quarter-century dedicated exclusively to camper innovation.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€75K",
    priceMin: 55000,
    dealers: "200+",
    dealerCount: 200,
    modelCount: 11,
    models: [
      { name: "F&S", series: "F&S", length: 600, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "V217 Sport Edition", series: "V-Series", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V114M Sport Edition", series: "V-Series", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V114 Sport Edition", series: "V-Series", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V114S Sport Edition", series: "V-Series", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Yucon",
    country: "Germany",
    founded: 2022,
    hq: "Marktschorgast, Germany",
    parent: "Independent",
    website: "yucon.de",
    positioning: "All models with 4x4 options. K-peak adventure series on Mercedes Sprinter.",
    platforms: ["ducato", "sprinter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€70K–€120K",
    priceMin: 70000,
    dealers: "20+",
    dealerCount: 20,
    modelCount: 10,
    models: [
      { name: "7.0 GD", series: "Yucon", length: 697, seats: 4, berths: 3, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "6.0 GD", series: "Yucon", length: 593, seats: 2, berths: 2, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "6.0 BD", series: "Yucon", length: 593, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "K-peak 7.0 GD", series: "K-peak", length: 593, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: false, fourx4: true },
      { name: "K-peak 6.0 BD", series: "K-peak", length: 593, seats: 4, berths: 4, chassis: "Mercedes Sprinter 4x4", poptop: true, fourx4: true },
      { name: "63 H", series: "Yucon", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "63 G", series: "Yucon", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "60 B", series: "Yucon", length: 600, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "54 B", series: "Yucon", length: 541, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Rapido",
    country: "France",
    founded: 1961,
    hq: "France",
    parent: "Rapido Group",
    website: "rapido-motorhome.co.uk",
    positioning: "Clever layouts with elegant, sophisticated curves. Premium French motorhomes.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€70K–€90K",
    priceMin: 70000,
    dealers: "100+",
    dealerCount: 100,
    modelCount: 3,
    models: [
      { name: "V68", series: "V-Series", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V65 XL", series: "V-Series", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "V55", series: "V-Series", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Joa Camp",
    country: "France",
    founded: 2019,
    hq: "France",
    parent: "Trigano Group",
    website: "joa-camp.com",
    positioning: "Young French brand. Affordable entry-level campervans.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€45K–€55K",
    priceMin: 45000,
    dealers: "50+",
    dealerCount: 50,
    modelCount: 3,
    models: [
      { name: "Fourgon 63T", series: "Fourgon", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "60G Van", series: "Fourgon", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Fourgon 54G", series: "Fourgon", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Mooveo",
    country: "Germany",
    founded: 2006,
    hq: "Germany",
    parent: "Pilote Group",
    website: "mooveo-wohnmobile.de",
    positioning: "Van series. Compact and mid-size campervans from the Pilote Group.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€50K–€65K",
    priceMin: 50000,
    dealers: "100+",
    dealerCount: 100,
    modelCount: 7,
    models: [
      { name: "Van 63XL", series: "Van", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Van 63EB", series: "Van", length: 636, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Van 60EB", series: "Van", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Van 60DB", series: "Van", length: 600, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
      { name: "Van 54DB", series: "Van", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Kompanja",
    country: "Germany",
    founded: 2016,
    hq: "Brühl, Germany",
    parent: "Independent",
    website: "kompanja.de",
    positioning: "More comfortable than a motorhome, more economical than an SUV. Fits conventional parking.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: true,
    priceRange: "€55K–€70K",
    priceMin: 55000,
    dealers: "10+",
    dealerCount: 10,
    modelCount: 1,
    models: [
      { name: "Zwei", series: "Kompanja", length: 541, seats: 4, berths: 2, chassis: "Fiat Ducato", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Rimor",
    country: "Italy",
    founded: 1978,
    hq: "Poggibonsi, Italy",
    parent: "Trigano Group",
    website: "rimor.it",
    positioning: "Functional and essential. Design solutions inspired by Made in Italy artisanship.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€50K–€65K",
    priceMin: 50000,
    dealers: "150+",
    dealerCount: 150,
    modelCount: 5,
    models: [
      { name: "Horus 95", series: "Horus", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Horus 54", series: "Horus", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Horus 45", series: "Horus", length: 600, seats: 4, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Horus 38", series: "Horus", length: 600, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Horus 12", series: "Horus", length: 541, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Bunkervan",
    country: "Spain",
    founded: 2020,
    hq: "Alpedrete, Madrid, Spain",
    parent: "Independent",
    website: "bunkervan.com",
    positioning: "Quality as a key value. From urban to off-road campervans.",
    platforms: ["transit"],
    has4x4: true,
    hasPoptop: false,
    priceRange: "€50K–€80K",
    priceMin: 50000,
    dealers: "5+",
    dealerCount: 5,
    modelCount: 6,
    models: [
      { name: "OFF Road", series: "OFF Road", length: 598, seats: 2, berths: 4, chassis: "Ford Transit 4x4", poptop: false, fourx4: true },
      { name: "Urban Maxi", series: "Urban", length: 541, seats: 4, berths: 4, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "Boston 4", series: "Boston", length: 541, seats: 4, berths: 4, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "Boston 2", series: "Boston", length: 541, seats: 2, berths: 4, chassis: "Ford Transit", poptop: false, fourx4: false },
      { name: "Urban 4", series: "Urban", length: 496, seats: 4, berths: 4, chassis: "Ford Transit Custom", poptop: false, fourx4: false },
      { name: "Urban 2", series: "Urban", length: 496, seats: 2, berths: 4, chassis: "Ford Transit Custom", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Julia Camper",
    country: "Spain",
    founded: 1999,
    hq: "Celrà, Girona, Spain",
    parent: "Independent",
    website: "juliacamper.com",
    positioning: "Wide range of camper vehicles manufactured in series. Spanish craftsmanship.",
    platforms: ["crafter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "€80K–€120K",
    priceMin: 80000,
    dealers: "5+",
    dealerCount: 5,
    modelCount: 1,
    models: [
      { name: "Yellowstone", series: "Yellowstone", length: 599, seats: 4, berths: 4, chassis: "VW Crafter / MAN TGE 4x4", poptop: true, fourx4: true },
    ]
  },
  {
    name: "Vanworx",
    country: "UK",
    founded: 2008,
    hq: "Portland, UK",
    parent: "Independent",
    website: "vanworx.co.uk",
    positioning: "Premium, custom built VW campers and sports vans. 15+ years of experience.",
    platforms: ["crafter"],
    has4x4: true,
    hasPoptop: true,
    priceRange: "£80K–£120K",
    priceMin: 80000,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 3,
    models: [
      { name: "4WD VW Crafter/MAN TGE", series: "Vanworx", length: 599, seats: 4, berths: 4, chassis: "VW Crafter / MAN TGE 4x4", poptop: true, fourx4: true },
      { name: "2WD VW Crafter/MAN TGE", series: "Vanworx", length: 599, seats: 4, berths: 4, chassis: "VW Crafter / MAN TGE", poptop: true, fourx4: false },
      { name: "2WD Crafter/TGE Lite", series: "Vanworx", length: 599, seats: 4, berths: 4, chassis: "VW Crafter / MAN TGE", poptop: true, fourx4: false },
    ]
  },
  {
    name: "Wildax",
    country: "UK",
    founded: 2006,
    hq: "Elland, West Yorkshire, UK",
    parent: "Independent",
    website: "wildaxmotorhomes.com",
    positioning: "Quality of build and value for money. British-built motorhomes.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "£60K–£80K",
    priceMin: 60000,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 3,
    models: [
      { name: "Constellation XL", series: "Constellation", length: 636, seats: 3, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Altair RS", series: "Altair", length: 684, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Altair RS Sport", series: "Altair", length: 684, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Affinity",
    country: "Poland",
    founded: 2020,
    hq: "Ozorków, Poland",
    parent: "Affinity RV",
    website: "affinity-rv.eu",
    positioning: "Dynamic growth. Polish-built campervans with diverse layouts.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€65K–€85K",
    priceMin: 65000,
    dealers: "10+",
    dealerCount: 10,
    modelCount: 6,
    models: [
      { name: "M Four", series: "M", length: 599, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "M Duo", series: "M", length: 684, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Five", series: "Standard", length: 636, seats: 5, berths: 5, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Three", series: "Standard", length: 636, seats: 4, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Duo", series: "Standard", length: 636, seats: 2, berths: 2, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "One", series: "Standard", length: 636, seats: 4, berths: 4, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "Freedom",
    country: "Poland",
    founded: 2019,
    hq: "Ozorków, Poland",
    parent: "Affinity RV",
    website: "freedom-rv.eu",
    positioning: "Swedish-Polish company. Second brand by Affinity RV.",
    platforms: ["ducato"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "€55K–€70K",
    priceMin: 55000,
    dealers: "5+",
    dealerCount: 5,
    modelCount: 2,
    models: [
      { name: "Freedom 636", series: "Freedom", length: 636, seats: 3, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
      { name: "Freedom 541", series: "Freedom", length: 541, seats: 3, berths: 3, chassis: "Fiat Ducato", poptop: false, fourx4: false },
    ]
  },
  {
    name: "MOS Adventure",
    country: "UK",
    founded: 2018,
    hq: "Powys, UK",
    parent: "Independent",
    website: "mosadventure.co.uk",
    positioning: "It's not just a van, it's a lifestyle. Custom builds for off-grid outdoor life.",
    platforms: ["sprinter"],
    has4x4: false,
    hasPoptop: false,
    priceRange: "£80K–£100K",
    priceMin: 80000,
    dealers: "Direct",
    dealerCount: 1,
    modelCount: 2,
    models: [
      { name: "Tor", series: "MOS", length: 697, seats: 4, berths: 4, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
      { name: "Nevis", series: "MOS", length: 697, seats: 2, berths: 2, chassis: "Mercedes Sprinter", poptop: false, fourx4: false },
    ]
  },
];
